<? if ($this->pageCount): ?>
    <span class="column">
        <? if (isset($this->previous)): ?>
            <a href="<?= $this->basePath() . '/branches/' . $this->actionName . '/page/' . $this->first; ?>">
                &laquo; First
            </a>
        <? else: ?>
            <span class="disabled">&laquo; First</span>
        <? endif; ?>
    </span>

    <span class="two column center">
        <? if (isset($this->previous)): ?>
            <a class="pagination-item" href="<?= $this->basePath() . '/branches/' . $this->actionName . '/page/' . $this->previous; ?>">
                &lt;
            </a>
        <? else: ?>
            <span class="disabled pagination-item">&lt;</span>
        <? endif; ?>

        <? foreach ($this->pagesInRange as $page): ?>
            <? if ($page != $this->current): ?>
                <a class="pagination-item" href="<?= $this->basePath() . '/branches/' . $this->actionName . '/page/' . $page; ?>">
                    <?= $page; ?>
                </a>
            <? else: ?>
                <span class="disabled pagination-item"><?= $page; ?></span>
            <? endif; ?>
        <? endforeach; ?>

        <? if (isset($this->next)): ?>
            <a class="pagination-item" href="<?= $this->basePath() . '/branches/' . $this->actionName . '/page/' . $this->next; ?>">
                &gt;
            </a>
        <? else: ?>
            <span class="disabled pagination-item">&gt;</span>
        <? endif; ?>
    </span>


    <span class="column right">
        <? if (isset($this->next)): ?>
            <a href="<?= $this->basePath() . '/branches/' . $this->actionName . '/page/' . $this->last; ?>">
                Last &raquo;
            </a>
        <? else: ?>
            <span class="disabled">Last &raquo;</span>
        <? endif; ?>
    </span>
<? endif; ?>
